import mock from './mock'

import './jwt'
import './select'
import './pages/faq'
import './apps/chat'
import './apps/email'
import './apps/invoice'
import './apps/userList'
import './apps/eCommerce'
import './pages/blog-data'
import './pages/pricing-data'
import './navbar/navbarSearch'
import './pages/knowledge-base'
import './cards/card-analytics'
import './cards/card-statistics'
import './pages/account-settings'
import './autoComplete/autoComplete'

mock.onAny().passThrough()
